server:
  port: 8081

logging:
  level:
    root: INFO
    com.abraham.payments: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: tech
    password: test
    driver.class: org.postgresql.Driver

  cloud:
    function:
      definition: payment-consumer;online-producer;offline-producer;failing-producer
    stream:
      kafka.bindings.payment-consumer-in-0.consumer.destinationIsPattern: true
      bindings:
        payment-consumer-in-0:
          destination: online|offline
          group: payment-processor
        online-producer-out-0:
          destination: online
        offline-producer-out-0:
          destination: offline
        failing-producer-out-0:
          destination: offline




